# Generated by Django 5.0.5 on 2024-07-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_primeirosemestre_segundosemestre_terceirosemestre_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='PrimeiroSemestre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='SegundoSemestre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='TerceiroSemestre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='Total',
            table=None,
        ),
    ]
