# Generated by Django 5.0.5 on 2024-07-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_primeirosemestre_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='PrimeiroSemestre',
            table='PrimeiroSemestre',
        ),
        migrations.AlterModelTable(
            name='SegundoSemestre',
            table='SegundoSemestre',
        ),
        migrations.AlterModelTable(
            name='TerceiroSemestre',
            table='TerceiroSemestre',
        ),
        migrations.AlterModelTable(
            name='Total',
            table='Total',
        ),
    ]
